### ISSUE TITLE
Issue during installation of requirements >> MySQL-python

### ISSUE THREAD

**Issue by sibe7691** [app-shack/django-project-template#1]
When installing requirements, this exception is thrown on the mysql entry.

```
Collecting MySQL-python (from mysql==0.0.1->-r requirements/base.txt (line 12))
  Using cached MySQL-python-1.2.5.zip
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/11/27qx0qps24g2mkzrw8vvpmbh0000gn/T/pip-build-yqtoqf_5/MySQL-python/setup.py", line 13, in <module>
        from setup_posix import get_config
      File "/private/var/folders/11/27qx0qps24g2mkzrw8vvpmbh0000gn/T/pip-build-yqtoqf_5/MySQL-python/setup_posix.py", line 2, in <module>
        from ConfigParser import SafeConfigParser
    ImportError: No module named 'ConfigParser'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/11/27qx0qps24g2mkzrw8vvpmbh0000gn/T/pip-build-yqtoqf_5/MySQL-python/
(hydra) simon hydra $ 
```

**Comment by flaeppe** [comment]
There's no requirement added for `MySQL` per default. This is probably an issue for the local python environment.

Does this happen when running the following, and having a clean pip environment? 

`bash <(curl -s https://raw.githubusercontent.com/app-shack/django-project-template/v1.0.0/init.sh)`

**Comment by sibe7691** [comment]
Tried it now, and it worked without problems. Closing for now.
